### ISSUE TITLE
Position Listener doesn't update the position (degreesPerSecound and material works)

### ISSUE THREAD

**Issue by wiizarrrd** [giandifra/arcore_flutter_plugin#123]
Position Listener doesn't update the position (degreesPerSecound and material works) :/

v 0.0.10

**Comment by wiizarrrd** [comment]
Update Position is not part of this plugin (yet)
Here is how I fixed it:
just edited ArCoreView.kt:

ln 19: import com.difrancescogianmarco.arcore_flutter_plugin.utils.DecodableUtils.Companion.parseVector3
ln 185: updatePosition(call,result)

uncomment function updatePosition at ln 571

**Comment by jakub-cosmose** [comment]
I don't think it's solved. The plugin still doesn't support handling position updates. Making it work requires forking the plugin and making custom modifications. Is there any reason why this code is still commented out?
