### ISSUE TITLE
Object is not abstract and does not implement abstract member public abstract fun onActivityCreated(@NonNull p0: Activity, @Nullable p1: Bundle?):

### ISSUE THREAD

**Issue by jreffitt** [giandifra/arcore_flutter_plugin#149]
I was trying to import the plugin and run a newly created flutter app.

I was getting this build error:
`Launching lib/main.dart on TC77 in debug mode...
e: /Users/johnreffitt/Projects/cto/arcore_flutter_plugin-0.0.11/android/src/main/kotlin/com/difrancescogianmarco/arcore_flutter_plugin/ArCoreView.kt: (245, 38): Object is not abstract and does not implement abstract member public abstract fun onActivityCreated(@NonNull p0: Activity, @Nullable p1: Bundle?): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: /Users/johnreffitt/Projects/cto/arcore_flutter_plugin-0.0.11/android/src/main/kotlin/com/difrancescogianmarco/arcore_flutter_plugin/ArCoreView.kt: (246, 13): 'onActivityCreated' overrides nothing
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'.  
> Compilation error. See log for more details                           
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 18s      `

If you notice, i switched from using the pub cache version of the plugin to one on disk.  I simply copied the cache version into a folder next to my project.

The fix for this was for me to modify file ArCoreView.kt ln 246.
from:
            override fun onActivityCreated(activity: Activity?, savedInstanceState: Bundle?) {
to:
            override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {

I was then able to build and run my newly created app with the arcore_flutter_plugin.

**Comment by naveenbharadwaj19** [comment]
It's a fatal error:
```
D:\OTHER FILES D\CS ALL FOLD\Flutter main sdk\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArCoreView.kt: (245, 38): Object is not abstract and does not implement abstract member public abstract fun onActivityCreated(@NonNull p0: Activity, @Nullable p1: Bundle?): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: D:\OTHER FILES D\CS ALL FOLD\Flutter main sdk\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArCoreView.kt: (246, 13): 'onActivityCreated' overrides nothing

FAILURE: Build failed with an exception.
```

**Comment by giandifra** [comment]
Fixed in 0.1.0-null-safety.3

**Comment by amir-msh** [comment]
Hi, I'm using the latest version of the package and I'm having the same exception, It's fatal but it's not solved yet!how's the status?
@giandifra

**Comment by amir-msh** [comment]
Hi, thanks for your great package, I'm using the latest version of the package and the latest version of Flutter but I still have the same exception, It's fatal but it's not solved yet! how's the status?
@giandifra
